### ISSUE TITLE
AttributeError: 'ChatOpenAI' object has no attribute 'get_llm_metadata'

### ISSUE THREAD

**Issue by handrew** [jerryjliu/llama_index#1094]
I was previously using a custom LLMPredictor from LangChain to use gpt-3.5-turbo to query embeddings (see below). That no longer works with the 0.5.x updates. How do I use 3.5 now :(? 

```
llm_predictor = LLMPredictor(llm=ChatOpenAI(**CHATGPT_KWARGS))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
index = GPTSimpleVectorIndex.from_documents(docs, service_context=service_context)
```

**Comment by jerryjliu** [comment]
@handrew what's the error you're getting? this looks roughly right to me

**Comment by handrew** [comment]
Relevant snippet:

```
    service_context = ServiceContext.from_defaults(llm_predictor=llm)
  File "/Users/handrew/env/lib/python3.10/site-packages/llama_index/indices/service_context.py", line 72, in from_defaults
    prompt_helper = prompt_helper or PromptHelper.from_llm_predictor(
  File "/Users/handrew/env/lib/python3.10/site-packages/llama_index/indices/prompt_helper.py", line 69, in from_llm_predictor
    llm_metadata = llm_predictor.get_llm_metadata()
AttributeError: 'ChatOpenAI' object has no attribute 'get_llm_metadata'
```

**Comment by jerryjliu** [comment]
from looking at your stack trace it says `ServiceContext.from_defaults(llm_predictor=llm)` - are you setting llm_predictor equal to the langchain llm? it should be our LLMPredictor class

**Comment by handrew** [comment]
It is indeed a langchain LLM. I didn't know you guys moved that in house. I can't find the documentation on the website—could you point me in the right direction?

**Comment by handrew** [comment]
Oh no, I got it. Sorry. Pasted the stack trace for a snippet of code that was not the one I pasted in this issue. This is resolved.

**Comment by jerryjliu** [comment]
np! glad it's resolved
