### ISSUE TITLE
Response content was truncated

### ISSUE THREAD

**Issue by progyoung** [jerryjliu/llama_index#1261]
Same as #660. But 
index = GPTSimpleVectorIndex.load_from_disk('index.json', llm_predictor=llm_predictor)
or
index.query("姓名是什么",  text_qa_template=get_prompt(), llm_predictor=llm_predictor)
doesn't work with version 0.5.18.

error ouput:
TypeError: BaseGPTIndex.__init__() got an unexpected keyword argument 'llm_predictor'

**Comment by medinamaria90** [comment]
The same!! 

TypeError: BaseGPTIndex.__init__() got an unexpected keyword argument 'llm_predictor'

I've been  having this problem.

By the way, I can't find a source with the models accepted in this API... only davinchi and chatgpt Turbo? Or can I use Ada?

**Comment by progyoung** [comment]
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
index = GPTSimpleVectorIndex.load_from_disk('index/index.json', service_context=service_context)

this issue had been solved.

**Comment by progyoung** [comment]
> 
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
index = GPTSimpleVectorIndex.load_from_disk('index/index.json', service_context=service_context)

**Comment by pinsystem** [comment]
Did you solve the response being truncated problem? It stays the same to me. If you don't mind, please share the code.

**Comment by progyoung** [comment]
> 

I had show the code in my previous answer. My case is related to Chinese. If your answer is in English and has been truncated, your problem may have exceeded the max token limit of model.

**Comment by Lekcy** [comment]
# customize the LLM settings
    llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003", max_tokens=2048))
    # load from disk and set the LLM predictor
    index = GPTSimpleVectorIndex.load_from_disk('index.json', llm_predictor=llm_predictor)
    response = index.query(input_text, response_mode="compact")


Hope this helps
