### ISSUE TITLE
"TransformQueryEngine" doesn't seem to exist?

### ISSUE THREAD

**Issue by janzheng** [jerryjliu/llama_index#1566]
`ImportError: cannot import name 'TransformQueryEngine' from 'llama_index.indices.query' (/home/runner/025-streamlit-llamaindex-starter/venv/lib/python3.8/site-packages/llama_index/indices/query/__init__.py`

Trying many variations of trying to import TransformQueryEngine from various tutorials, either using `
from llama_index.indices.query import TransformQueryEngine` or `gpt_index.query_engine.transform_query_engine.TransformQueryEngine` but alas, none of these variations seem to exist.

Is the documentation out of date in every instance this module is being referenced in?

**Comment by Art9681** [comment]
I too have wasted too much time messing with this tool. The documentation appears to be out of date as most of the examples I am attempting to run are mostly failing for the same reasons. 

Perhaps the best use case for this tool is to have it keep its own documentation up to date. That would be solving a real problem an prove it is useful in a real world use case.

**Comment by logan-markewich** [comment]
@janzheng are you on the latest version?

This import should work in the `0.6.0-aplha3`: `from llama_index.query_engine.transform_query_engine import TransformQueryEngine`

**Comment by logan-markewich** [comment]
@Art9681 if there's a problem with the docs, let me know 👍🏻 There was just a major update to 0.6.0-alpha which changed a few things.

Either make sure your llama index version is installed with `pip install --upgarde llama-index==0.6.0.alpha3`

Or, you can view the older docs here: https://t.co/8SVqjJNXQp

**Comment by Art9681** [comment]
@logan-markewich Thank you for quick reply. I will take a look at your suggestion. I apologize for my demeanor in my previous comment. It was one of those frustrating moments dealing with new technology that is rapidly evolving. I understand it is early and things are fluid. Thanks again for the help.

**Comment by jerryjliu** [comment]
> Trying many variations of trying to import TransformQueryEngine from various tutorials, either using ` from llama_index.indices.query import TransformQueryEngine` or `gpt_index.query_engine.transform_query_engine.TransformQueryEngine` but alas, none of these variations seem to exist.

Just to flag, if you're on llama-index<0.6.0, we have old docs here: https://gpt-index.readthedocs.io/en/v0.5.27/

In the meantime please upgrade to llama-index 0.6.0.alpha3 if you're following the latest docs https://gpt-index.readthedocs.io/en/latest/

**Comment by K-Irwin8** [comment]
jerry liu you are a god!
