### ISSUE TITLE
Custom model issue when llama-index is upgraded to 0.5.x

### ISSUE THREAD

**Issue by paulsiu1887** [jerryjliu/llama_index#1033]
I upgraded llama-index from 0.4.28 to 0.5.5. I got the following error on the following code:

```
import os
import torch
from llama_index import SimpleDirectoryReader, LangchainEmbedding, GPTSimpleVectorIndex, PromptHelper
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
from llama_index import LLMPredictor
from langchain.llms.base import LLM
from transformers import pipeline

class FlanLLM(LLM):
    model_name = 'google/flan-t5-large'
    pipeline = pipeline('text2text-generation', model = model_name, device = "cpu", model_kwargs={'torch_dtype': torch.bfloat16})
    
    def _call(self, prompt, stop=None):
        return self.pipeline(prompt, max_length=9999)[0]['generated_text']

    def _identifying_params(self):
        return {'name_of_model': self.model.name}
    
    def _llm_type(self):
        return "custom"
    
llm_predictor = LLMPredictor(llm=FlanLLM())
hfemb = HuggingFaceEmbeddings()
embed_model = LangchainEmbedding(hfemb)
documents = SimpleDirectoryReader('Data').load_data()

max_input_size = 714
num_output=256
max_chuck_overlap = 0
prompt_helper = PromptHelper(max_input_size, num_output, max_chuck_overlap)
index = GPTSimpleVectorIndex(documents, embed_model = embed_model, llm_predictor = llm_predictor, prompt_helper = prompt_helper)


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [5], line 5
      3 max_chuck_overlap = 0
      4 prompt_helper = PromptHelper(max_input_size, num_output, max_chuck_overlap)
----> 5 index = GPTSimpleVectorIndex(documents, embed_model = embed_model, llm_predictor = llm_predictor, prompt_helper = prompt_helper)
      6 #index.save_to_disk('index.json')

File /opt/conda/lib/python3.9/site-packages/llama_index/indices/vector_store/vector_indices.py:94, in GPTSimpleVectorIndex.__init__(self, nodes, index_struct, service_context, text_qa_template, simple_vector_store_data_dict, **kwargs)
     86     simple_vector_store_data_dict = {
     87         "embedding_dict": index_struct.embeddings_dict,
     88     }
     90 vector_store = SimpleVectorStore(
     91     simple_vector_store_data_dict=simple_vector_store_data_dict
     92 )
---> 94 super().__init__(
     95     nodes=nodes,
     96     index_struct=index_struct,
     97     service_context=service_context,
     98     text_qa_template=text_qa_template,
     99     vector_store=vector_store,
    100     **kwargs,
    101 )
    103 # TODO: Temporary hack to also store embeddings in index_struct
    104 embedding_dict = vector_store._data.embedding_dict

File /opt/conda/lib/python3.9/site-packages/llama_index/indices/vector_store/base.py:58, in GPTVectorStoreIndex.__init__(self, nodes, index_struct, service_context, text_qa_template, vector_store, use_async, **kwargs)
     56 self.text_qa_template = text_qa_template or DEFAULT_TEXT_QA_PROMPT
     57 self._use_async = use_async
---> 58 super().__init__(
     59     nodes=nodes,
     60     index_struct=index_struct,
     61     service_context=service_context,
     62     **kwargs,
     63 )

TypeError: __init__() got an unexpected keyword argument 'embed_model'
```

The code worked in 0.4.28, but appears to start failing when we upgraded version to 0.5.x. Is there something more we have to do now for 0.5.x? Note that langchain version is 0.0.127. Note that SimpleDirectoryReader is just loading plain text files.

**Comment by logan-markewich** [comment]
@paulsiu1887 in 0.5.X, there were many changes. Check out the docs: https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#customizing-llm-s

Specifically you'll need the new ServiceContext object

`service_context =ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model, prompt_helper=prompt_helper)`
`index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)`

**Comment by logan-markewich** [comment]
@paulsiu1887 the LLM and embeddings models are separate.

Here's two docs pages that might help 
https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model

https://gpt-index.readthedocs.io/en/latest/how_to/customization/embeddings.html#custom-embeddings

**Comment by paulsiu1887** [comment]
Thanks!
I did see the custom embedding page, but when I attempt to embed the index, I got an error that seems to imply that I did not setup the predicator. but your comment indicate I need to setup the LLM and the embedding when I call create vector index.

**Comment by logan-markewich** [comment]
@paulsiu1887 yea while the LLM might not be used during index construction, it's still instantiated. And if you don't pass in an LLM predictor, it defaults to using OpenAI 

Glad this helped though! 💪
