### ISSUE TITLE
No attribute "as_query_engine" GPTkeywordTableIndex

### ISSUE THREAD

**Issue by lborcard** [jerryjliu/llama_index#2539]
HI,

I really love your tool and would like to use to parse pdf. Nonetheless I am getting this error message following this cell:
```
# build keyword index
documents = SimpleDirectoryReader('data').load_data()
index = GPTKeywordTableIndex.from_documents(documents)

query_engine = index.as_query_engine()

AttributeError: 'GPTKeywordTableIndex' object has no attribute 'as_query_engine'
```

I tried with GPTSimpleKeywordTableIndex and I get the same error message,

thank you for your help and for sharing this tool set of tools,

**Comment by lborcard** [comment]
Sorry for closing the error message changed to `No module named 'llama_index.query_engine'`

**Comment by jerryjliu** [comment]
Hello! @iblisylvie are you on the latest version? Try upgrading to 0.6.1

**Comment by lborcard** [comment]
The second error message was after the Update to 0.6.1

**Comment by Disiok** [comment]
Tried reproducing, but could not. 

Going to close this now. @lborcard if you are still having issues, please re-open with details to reproduce.
