### ISSUE TITLE
[Question]: about milvus version

### ISSUE THREAD

**Issue by JDZW2014** [jerryjliu/llama_index#7779]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Thanks for your great work!
I am work with llama_index and milvus and meet "ImportError: cannot import name 'MilvusClient' from 'pymilvus'".
I wandor to know which milvus version should we use?  
 The current version is pymilvus-2.2.0 and llama_index=0.8.29.post1

**Comment by logan-markewich** [comment]
@JDZW2014 seems to work with the latest -- ` pymilvus-2.3.1`

**Comment by JDZW2014** [comment]
use pymilvus=2.2.0 pymilvus get error ： ImportError: cannot import name 'MilvusClient' from 'pymilvus' 
use pymilvus=2.3.0 or 2.3.1 get error：pymilvus.exceptions.MilvusException: <MilvusException: (code=1, message=this version of sdk is incompatible with server, please downgrade your sdk or upgrade your server)>
