### ISSUE TITLE
ModuleNotFoundError: No module named 'gpt_index'

### ISSUE THREAD

**Issue by smcady** [jerryjliu/llama_index#1863]
Hi, friends.  I am trying to run the notebook example at [examples/vector_indices/PineconeIndexDemo.ipynb ](https://github.com/jerryjliu/llama_index/blob/main/examples/vector_indices/PineconeIndexDemo.ipynb), and am getting the following error trying to import StorageContext:

```
ModuleNotFoundError                      
Traceback (most recent call last)
[<ipython-input-3-0547849ae4a2>](https://localhost:8080/#) in <cell line: 2>()
      1 # initialize without metadata filter
----> 2 from gpt_index.storage.storage_context import StorageContext
      3 
      4
      5 vector_store = PineconeVectorStore(

ModuleNotFoundError: No module named 'gpt_index'
```

I have received this error both locally now, and in a codespace that I believe is properly configured with the following dependencies:

- Python 3.10.4
- Flask 2.2.2
- llama_index 0.5.27
- pinecone-client
- wget
- langchain
- openai

Any ideas? Thanks!

**Comment by smcady** [comment]
I had the same thought... but, unfortunately:

```
Exception has occurred: ModuleNotFoundError
No module named 'llama_index.storage'
  File "/workspaces/codespaces-flask/app.py", line 26, in <module>
    from llama_index.storage.storage_context import StorageContext
ModuleNotFoundError: No module named 'llama_index.storage'  
```

an no worries at all!  thanks for your help

**Comment by logan-markewich** [comment]
@smcady you'll want the newer version of llama index for storage context (currently its in alpha)

`pip install llama-index==0.6.0.alpha6`

**Comment by smcady** [comment]
Unfortunately, after upgrade to 0.6.0.alpha, 
```
Exception has occurred: ImportError
cannot import name 'GPTSimpleVectorIndex' from 'llama_index' (/home/codespace/.python/current/lib/python3.10/site-packages/llama_index/__init__.py)
  File "/workspaces/codespaces-flask/app-old2.py", line 18, in <module>
    from llama_index import (GPTListIndex, GPTSimpleVectorIndex, LLMPredictor,
ImportError: cannot import name 'GPTSimpleVectorIndex' from 'llama_index' (/home/codespace/.python/current/lib/python3.10/site-packages/llama_index/__init__.py)
```

**Comment by logan-markewich** [comment]
It has been renamed to GPTVectorStoreIndex

I highly recommend checking out the latest docs, a few interfaces changed

https://gpt-index.readthedocs.io/en/stable/guides/primer/usage_pattern.html

**Comment by smcady** [comment]
Ahh.  Thank you, @logan-markewich

**Comment by Disiok** [comment]
@smcady thanks for your interest and apologies for the doc/lib mismatch. 

We were in the process of a pretty big refactor, so didn't synchronize the two super well.  Right now if you pip install, you should get the latest 0.6.0 version, which should match what's on https://gpt-index.readthedocs.io/. 

Going to close this issue for now, definitely feel free to open another one if issues pop up!

**Comment by Jeewant-Jaat** [comment]
pip install gpt_index==0.4.15

**Comment by croshado** [comment]
thanks @Jeewant-Balyan  it worked
